### ISSUE TITLE
Gameplay in DM

### ISSUE THREAD

**Issue by schrmh** [Ratismal/UNO#5]
It's a little bit of a pain to constantly switch between DM and server.
You should make it possible to play the game without the need to switch.
How it is solved currently is suboptimal anyways: The bot sends you your hand without telling you which instance of the game (server and channel) this hand belongs to.

**Comment by Ratismal** [comment]
Playing cards in DMs defeats the social aspect of the game. If you're playing multiple games at once, that's your own problem.

**Comment by schrmh** [comment]
No, but I am playing with my smartphone. The example with multiple servers/channels was just to bring another factor into this.
Also you could copy what you post to the server to the DM of the users. I don't see why this would destroy the social aspect. In case the user wants to write something he could switch to the server or well.. simply use the VC.
