### ISSUE TITLE
Gameplay via Reactions

### ISSUE THREAD

**Issue by schrmh** [Ratismal/UNO#6]
Instead of typing the bot should add possible reactions to the message where you are informed that it is your turn. It just saves a lot of time; especially on mobile.
In case that you will solve the DM/Server switching issue you could also only display reactions that are currently possible for the specific user.

**Comment by Ratismal** [comment]
So, what? You want the bot to put the reactions of every single card on its message for you to click on? That's completely unrealistic.

**Comment by schrmh** [comment]
I tested it and on a server I run I can add 19 reactions to a message.
That's enough to cover all cards:
10 for 0-9
4 for colours
5 for stop, reverse, +2, +4, colour change

**Comment by Ratismal** [comment]
19 reactions would also take 19 seconds to apply. That's a lot of API requests and waiting for each turn. I'm not going to implement this.
